name: Development deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        type: text
        required: true

jobs:
  build-test:
    uses: ./.github/workflows/deploy-template.yml
    with:
      aws-bucket: ${{ vars.AWS_DEV_S3_BUCKET }}
      aws-region: ${{ vars.AWS_REGION }}
      deploy-branch: ${{ inputs.branch }}
      deploy-source-dir: ${{ vars.DEPLOY_SOURCE_DIR }}
      fastly-service-id: ${{ vars.FASTLY_DEV_SERVICE_ID }}
      site-config-json: '{"env": "dev"}'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      fastly-purge-api-token: ${{ secrets.FASTLY_PURGE_API_TOKEN }}
      mapbox-token: ${{ secrets.VITE_MAPBOX_TOKEN }}
